import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:web_ui_plugins/web_ui_plugins.dart';

import '../features/clients/client_plugin.dart';
import '../features/staff/staff_plugin.dart';

/// All app wiring in one place.
/// main.dart calls [ShalloonBootstrap.run].
class ShalloonBootstrap {
  ShalloonBootstrap._();

  /// Firebase options — generated by FlutterFire CLI for your project.
  /// Replace with your own options or import from firebase_options.dart.
  static FirebaseOptions get _firebaseOptions => const FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    authDomain: 'YOUR_AUTH_DOMAIN',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    messagingSenderId: 'YOUR_SENDER_ID',
    appId: 'YOUR_APP_ID',
  );

  /// Local setup for development — initializes Firebase, sets a dev user, and registers plugins.
  static Future<void> run({bool useEmulators = false}) async {
    // Step 1: Initialize framework + Firebase
    await AppBootstrap.initialize(
      config: BootstrapConfig(
        initializeFirebase: () async {
          await Firebase.initializeApp(options: _firebaseOptions);
          if (useEmulators) {
            FirebaseFunctions.instance.useFunctionsEmulator('localhost', 5001);
            FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
            FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
          }
        },
        defaultPermissionPolicy: const OpenPermissionPolicy(),
      ),
    );

    // Step 2: Set active user (replace with real auth state listener)
    PermissionMiddleware.instance.setUser(
      const UserIdentity(
        userId: 'dev-user',
        persona: 'admin', // ShalloonPersona.admin.label
        email: 'dev@shalloon.app',
      ),
    );

    // Step 3: Register plugins — this is the entire app configuration
    await AppBootstrap.registerPlugins([staffPlugin, clientPlugin]);
  }
}
